[tasks.update_toolchain]
command = "rustup"
args = ["update"]

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.update]
command = "cargo"
args = ["update"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.reboot]
dependencies = [
    "update_toolchain",
    "format",
    "clean",
    "update",
    "build",
    "test",
    "audit",
    "clippy"
]